/*globals define, _, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 0.1.0 from webgme on Mon Sep 28 2015 18:33:34 GMT-0500 (CDT).
 */

define([
  "js/PanelBase/PanelBaseWithHeader",
  "js/PanelManager/IActivePanel",
  "js/Widgets/OtherViz/OtherVizWidget",
  "./OtherVizControl",
], function (
  PanelBaseWithHeader,
  IActivePanel,
  OtherVizWidget,
  OtherVizControl
) {
  "use strict";

  var OtherVizPanel;

  OtherVizPanel = function (layoutManager, params) {
    var options = {};
    //set properties from options
    options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = "OtherVizPanel";
    options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

    //call parent's constructor
    PanelBaseWithHeader.apply(this, [options, layoutManager]);

    this._client = params.client;

    //initialize UI
    this._initialize();

    this.logger.debug("ctor finished");
  };

  //inherit from PanelBaseWithHeader
  _.extend(OtherVizPanel.prototype, PanelBaseWithHeader.prototype);
  _.extend(OtherVizPanel.prototype, IActivePanel.prototype);

  OtherVizPanel.prototype._initialize = function () {
    var self = this;

    //set Widget title
    this.setTitle("");

    this.widget = new OtherVizWidget(this.logger, this.$el);

    this.widget.setTitle = function (title) {
      self.setTitle(title);
    };

    this.control = new OtherVizControl({
      logger: this.logger,
      client: this._client,
      widget: this.widget,
    });

    this.onActivate();
  };

  /* OVERRIDE FROM WIDGET-WITH-HEADER */
  /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
  OtherVizPanel.prototype.onReadOnlyChanged = function (isReadOnly) {
    //apply parent's onReadOnlyChanged
    PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);
  };

  OtherVizPanel.prototype.onResize = function (width, height) {
    this.logger.debug("onResize --> width: " + width + ", height: " + height);
    this.widget.onWidgetContainerResize(width, height);
  };

  /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
  OtherVizPanel.prototype.destroy = function () {
    this.control.destroy();
    this.widget.destroy();

    PanelBaseWithHeader.prototype.destroy.call(this);
    WebGMEGlobal.KeyboardManager.setListener(undefined);
    WebGMEGlobal.Toolbar.refresh();
  };

  OtherVizPanel.prototype.onActivate = function () {
    this.widget.onActivate();
    this.control.onActivate();
    WebGMEGlobal.KeyboardManager.setListener(this.widget);
    WebGMEGlobal.Toolbar.refresh();
  };

  OtherVizPanel.prototype.onDeactivate = function () {
    this.widget.onDeactivate();
    this.control.onDeactivate();
    WebGMEGlobal.KeyboardManager.setListener(undefined);
    WebGMEGlobal.Toolbar.refresh();
  };

  return OtherVizPanel;
});
