// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
"use strict";

var config = require("webgme/config/config.default"),
  validateConfig = require("webgme/config/validator");

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push("src/plugin");
config.addOn.basePaths.push("src/addOn");
config.seedProjects.basePaths.push(
  "/home/irishninja/programming/webgme-setup-tool/test/res/OtherProject/src/seed/OtherSeed"
);
config.seedProjects.basePaths.push(
  "/home/irishninja/programming/webgme-setup-tool/test/res/OtherProject/src/seed/alreadyExists"
);

config.addOn.enable = true;

validateConfig(config);
module.exports = config;
