// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';

var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

config.plugin.basePaths.push("src/plugin");

config.addOn.enable = true

config.addOn.basePaths.push("src/addon/OtherAddOn");

validateConfig(config);
module.exports = config;
