/*globals define*/
/*jshint node:true, browser:true*/

/**
* Generated by PluginGenerator from webgme on Wed Jul 29 2015 20:28:43 GMT-0500 (CDT).
*/

define([
    'plugin/PluginConfig',
    'plugin/PluginBase',
], function (PluginConfig, PluginBase) {
    'use strict';

    /**
    * Initializes a new instance of RemoveFromPlugin.
    * @class
    * @augments {PluginBase}
    * @classdesc This class represents the plugin RemoveFromPlugin.
    * @constructor
    */
    var RemoveFromPlugin = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        this.metaTypes = MetaTypes;
    };

    // Prototypal inheritance from PluginBase.
    RemoveFromPlugin.prototype = Object.create(PluginBase.prototype);
    RemoveFromPlugin.prototype.constructor = RemoveFromPlugin;

    /**
    * Gets the name of the RemoveFromPlugin.
    * @returns {string} The name of the plugin.
    * @public
    */
    RemoveFromPlugin.prototype.getName = function () {
        return 'ComponentDisabler';
    };

    /**
    * Gets the semantic version (semver.org) of the RemoveFromPlugin.
    * @returns {string} The version of the plugin.
    * @public
    */
    RemoveFromPlugin.prototype.getVersion = function () {
        return '0.1.0';
    };

    RemoveFromPlugin.prototype.getConfigStructure = function () {
        // Get the field and the attribute
        return [
            { name: 'field',
              displayName: 'Field',
              description: 'Field of root node to add to',
              value: null,
              valueType: 'string',
              readOnly: false },
            { name: 'attribute',
              displayName: 'Attribute',
              description: 'Attribute to add to field',
              value: '',
              valueType: 'string',
              readOnly: false }
        ];
    };

    /**
    * Main function for the plugin to execute. This will perform the execution.
    * Notes:
    * - Always log with the provided logger.[error,warning,info,debug].
    * - Do NOT put any user interaction logic UI, etc. inside this method.
    * - callback always has to be called even if error happened.
    *
    * @param {function(string, plugin.PluginResult)} callback - the result callback
    */
    RemoveFromPlugin.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            currentConfig = self.getCurrentConfig(),
            field = currentConfig.field,
            attribute = currentConfig.attribute,
            index,
            attributes;

        self.updateMETA(self.metaTypes);
        if (!currentConfig.field) {
            self.result.setSuccess(false);
            return callback('No field provided', self.result);
        }

        // Add to root node's "field" attribute
        attributes = self.core.getAttribute(self.rootNode, field).split(' ');
        index = attributes.indexOf(attribute);
        if (index === -1) {
            attributes.splice(index,1);
        }
        self.core.setAttribute(self.rootNode, field, attributes.join(' '));

        // This will save the changes. If you don't want to save;
        // exclude self.save and call callback directly from this scope.
        self.result.setSuccess(true);
        self.save('Removed '+attribute+' from '+field, function (err) {
            callback(null, self.result);
        });
    };

    return RemoveFromPlugin;
});
