/*jshint node:true, mocha:true*/
/**
 * Generated by PluginGenerator from webgme on Wed Aug 19 2015 15:04:06 GMT-0500 (Central Daylight Time).
 */

'use strict';
var testFixture = require('../res/globals'),
    path = require('path');

describe('AddToPlugin', function () {
    var Q = require('q'),
        WEBGME_ROOT = path.join(__dirname, '..', '..', 'node_modules', 'webgme'),
        gmeConfig = testFixture.getGmeConfig(),
        expect = testFixture.expect,
        logger = testFixture.logger.fork('AddToPlugin'),
        PluginCliManager = testFixture.WebGME.PluginCliManager,
        projectName = 'testProject',
        pluginName = 'AddToPlugin',
        Core = testFixture.requirejs('common/core/core'),
        assert = require('assert'),
        project,
        gmeAuth,
        storage,
        FIELD = 'validPlugins',
        ATTRIBUTE = 'testPlugin',
        commitHash;

    var executePluginAndGetCore = function(context, callback) {
        var manager = new PluginCliManager(null, logger, gmeConfig),
            pluginConfig = {
                field: FIELD,
                attribute: ATTRIBUTE
            };
        manager.executePlugin(pluginName, pluginConfig, context, function (err, pluginResult) {
            expect(err).to.equal(null);
            expect(typeof pluginResult).to.equal('object');
            expect(pluginResult.success).to.equal(true);

            context.core = new Core(project, {globConf: gmeConfig, logger: logger});

            context.project.getBranchHash(context.branchName)
                .then(function (commitHash) {
                    context.commitHash = commitHash;
                    return Q.ninvoke(context.project, 'loadObject', commitHash);
                })
                .then(function (commitObject) {
                    var rootDeferred = Q.defer();
                    logger.debug('commitObject loaded', {metadata: commitObject});
                    context.core.loadRoot(commitObject.root, function (err, rootNode) {
                        if (err) {
                            rootDeferred.reject(err);
                        } else {
                            logger.debug('rootNode loaded');
                            rootDeferred.resolve(rootNode);
                        }
                    });

                    return rootDeferred.promise;
                })
                .nodeify(callback);
        });
    };

    before(function (done) {
        process.chdir(WEBGME_ROOT);
        testFixture.clearDBAndGetGMEAuth(gmeConfig, projectName)
            .then(function (gmeAuth_) {
                gmeAuth = gmeAuth_;
                // This uses in memory storage. Use testFixture.getMongoStorage to persist test to database.
                storage = testFixture.getMemoryStorage(logger, gmeConfig, gmeAuth);
                return storage.openDatabase();
            })
            .then(function () {
                var importParam = {
                    projectSeed: path.join(testFixture.SEED_DIR, 'EmptyProject.webgmex'),
                    projectName: projectName,
                    branchName: 'master',
                    logger: logger,
                    gmeConfig: gmeConfig
                };

                return testFixture.importProject(storage, importParam);
            })
            .then(function (importResult) {
                project = importResult.project;
                commitHash = importResult.commitHash;
                return project.createBranch('test', commitHash);
            })
            .nodeify(done);
    });

    after(function (done) {
        storage.closeDatabase()
            .then(function () {
                return gmeAuth.unload();
            })
            .nodeify(done);
    });

    it('should add plugin to validPlugins if it does not exist', function (done) {
        var context = {
                project: project,
                commitHash: commitHash,
                branchName: 'test',
                activeNode: '/960660211',
                core: null
            };

        executePluginAndGetCore(context, function (err, rootNode) {
            // Check that 'testPlugin' has been added to 'validPlugins' 
            // on the root node
            var attributes = context.core.getRegistry(rootNode, FIELD).split(' ');
            assert.notEqual(attributes.indexOf(ATTRIBUTE), -1);
            done();
        });
    });

    it('should not add plugin to validPlugins if it already exists', function (done) {
        var context = {
                project: project,
                commitHash: commitHash,
                branchName: 'test',
                activeNode: '/960660211',
                core: null
            },
            attributes,
            count;

        executePluginAndGetCore(context, function (err, rootNode) {
            attributes = context.core.getRegistry(rootNode, FIELD).split(' ');
            count = attributes.length;
            assert.notEqual(attributes.indexOf(ATTRIBUTE), -1);
            executePluginAndGetCore(context, function (err, rootNode) {
                // Check that 'testPlugin' has been added to 'validPlugins' 
                // on the root node
                attributes = context.core.getRegistry(rootNode, FIELD).split(' ');
                assert.equal(attributes.length, count);
                done();
            });
        });
    });

});
