// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';



var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');


// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push('src/plugins');
config.addOn.basePaths.push('src/addOns/MyAddon');
config.seedProjects.basePaths.push('src/seeds/test');

config.addOn.enable = true

validateConfig(config);
module.exports = config;
